git clone https://github.com/juamar/ORMLite.git
git clone https://github.com/juamar/Playing-with-AndroidNetwork.git
git clone https://github.com/juamar/Consuming-Content-Providers.git
git clone https://github.com/juamar/PlayingWithMenus.git
git clone https://github.com/juamar/PlayingWithInternalStorage.git
git clone https://github.com/juamar/SnackBar-and-Toast-Demos.git
git clone https://github.com/juamar/playingWithWebViews.git
git clone https://github.com/juamar/DateTimePickerDialogs.git
git clone https://github.com/juamar/PlayingWithDialogs.git
git clone https://github.com/juamar/SceneTransitions.git
git clone https://github.com/juamar/TransitionDemo.git
git clone https://github.com/juamar/DurationTextView.git
git clone https://github.com/juamar/ReceivingImplicitIntent.git
git clone https://github.com/juamar/ImplicitIntents.git
git clone https://github.com/juamar/AnswerTheQuestion.git
git clone https://github.com/juamar/PlayingWithListViews.git
git clone https://github.com/juamar/CardDemo.git
git clone https://github.com/juamar/RegisterActivityExample.git
git clone https://github.com/juamar/FragmentLifeCicle.git
git clone https://github.com/juamar/FragmentExample.git
git clone https://github.com/juamar/HelloWorld3.git
git clone https://github.com/juamar/AndroidStateChanges.git
git clone https://github.com/juamar/JavaExamples.git
git clone https://github.com/juamar/GanaderiaHerencia.git
git clone https://github.com/juamar/Ganaderia2.git
git clone https://github.com/juamar/PlayingWithGradle.git

